In [19]:
import pandas as pd
import numpy as np

In [20]:
data = pd.read_csv('../Data_bases/ndtv_data_final.csv')

In [21]:
data = data.drop('Unnamed: 0', axis=1)

In [22]:
cols = [] 
for col in data.columns: 
    cols.append(col.lower().replace(' ', '_')) 
data.columns = cols

data.head()

,name,brand,model,battery_capacity_(mah),screen_size_(inches),touchscreen,resolution_x,resolution_y,processor,ram_(mb),...,rear_camera,front_camera,operating_system,wi-fi,bluetooth,gps,number_of_sims,3g,4g/_lte,price
0,OnePlus 7T Pro McLaren Edition,OnePlus,7T Pro McLaren Edition,4085,6.67,Yes,1440,3120,8,12000,...,48.0,16.0,Android,Yes,Yes,Yes,2,Yes,Yes,58998
1,Realme X2 Pro,Realme,X2 Pro,4000,6.50,Yes,1080,2400,8,6000,...,64.0,16.0,Android,Yes,Yes,Yes,2,Yes,Yes,27999
2,iPhone 11 Pro Max,Apple,iPhone 11 Pro Max,3969,6.50,Yes,1242,2688,6,4000,...,12.0,12.0,iOS,Yes,Yes,Yes,2,Yes,Yes,106900
3,iPhone 11,Apple,iPhone 11,3110,6.10,Yes,828,1792,6,4000,...,12.0,12.0,iOS,Yes,Yes,Yes,2,Yes,Yes,62900
4,LG G8X ThinQ,LG,G8X ThinQ,4000,6.40,Yes,1080,2340,8,6000,...,12.0,32.0,Android,Yes,Yes,Yes,1,No,No,49990

In [23]:
data['price'] = data['price']*0.012
data['price'] = data['price'].round(2)
def format_value(val):
    return '{:.2f}'.format(val)

data['price'] = data['price'].map(format_value)

data['price'] = data['price'].astype(float)

In [24]:
data = data.dropna(axis=1)

In [25]:
bin_prices=[5.93, 200, 400, 600, 800, 1000, 2099.88]
bin_ranges=['<200€', '200-400€', '400-600€', '600-800€', '800-1000€', '1000+€']
data['price_ranges']=pd.cut(data['price'], bins = bin_prices,
                                               labels = bin_ranges)

In [26]:
data['screen_size_(inches)'].describe()

count    1359.000000
mean        5.291310
std         0.671357
min         2.400000
25%         5.000000
50%         5.200000
75%         5.700000
max         7.300000
Name: screen_size_(inches), dtype: float64

In [27]:
bin_size=[2.3, 3.0,4.0,5.0,6.0,7.3]
bin_size_range=['2.3-3.0(inches)', '3.0-4.0(inches)', '4.0-5.0(inches)', '5.0-6.0(inches)', '6+(inches)']
data['screen_size_range']=pd.cut(data['screen_size_(inches)'], bins = bin_size,
                                               labels = bin_size_range)

In [28]:
data['battery_capacity_(mah)'].describe()

count    1359.000000
mean     2938.489330
std       873.514133
min      1010.000000
25%      2300.000000
50%      3000.000000
75%      3500.000000
max      6000.000000
Name: battery_capacity_(mah), dtype: float64

In [29]:
bin_bat=[1010.0, 2300.0,3000.0,3500.0, 4500.0,6000.0]
bin_bat_range=['1010-2300(mah)', '2300-3000(mah)', '3000-3500(mah)', '3500-4500(mah)', '4500-6000(mah)']
data['battery_capacity_range']=pd.cut(data['battery_capacity_(mah)'], bins = bin_bat,
                                               labels = bin_bat_range)

In [30]:
data['rear_camera'].describe()

count    1359.000000
mean       12.070199
std         8.948337
min         0.000000
25%         8.000000
50%        12.200000
75%        13.000000
max       108.000000
Name: rear_camera, dtype: float64

In [31]:
data['rear_camera'].unique()

array([ 48. ,  64. ,  12. ,  16. ,  40. ,  12.2,  13. ,  12.3,  23. ,
        21. ,  32. ,  24. ,  20. ,  19. ,   2. ,  18. ,   8. ,  20.7,
         5. ,  10. ,  13.1,   8.7,   3. ,  41. ,   3.2, 108. ,  25. ,
         0. ,  21.5,   0.3,  15. ,  13.2])

In [32]:
bin_cam=[0,24,32,48,64,108]
bin_cam_range=['0-24(mp)', '24-32(mp)', '32-48(mp)', '48-64(mp)', '64+(mp)']
data['rear_camera_range']=pd.cut(data['rear_camera'], bins = bin_cam,
                                               labels = bin_cam_range)

In [34]:
data = data.dropna()

In [35]:
data.head()

,name,brand,model,battery_capacity_(mah),screen_size_(inches),touchscreen,resolution_x,resolution_y,processor,ram_(mb),...,bluetooth,gps,number_of_sims,3g,4g/_lte,price,price_ranges,screen_size_range,battery_capacity_range,rear_camera_range
0,OnePlus 7T Pro McLaren Edition,OnePlus,7T Pro McLaren Edition,4085,6.67,Yes,1440,3120,8,12000,...,Yes,Yes,2,Yes,Yes,707.98,600-800€,6+(inches),3500-4500(mah),32-48(mp)
1,Realme X2 Pro,Realme,X2 Pro,4000,6.50,Yes,1080,2400,8,6000,...,Yes,Yes,2,Yes,Yes,335.99,200-400€,6+(inches),3500-4500(mah),48-64(mp)
2,iPhone 11 Pro Max,Apple,iPhone 11 Pro Max,3969,6.50,Yes,1242,2688,6,4000,...,Yes,Yes,2,Yes,Yes,1282.80,1000+€,6+(inches),3500-4500(mah),0-24(mp)
3,iPhone 11,Apple,iPhone 11,3110,6.10,Yes,828,1792,6,4000,...,Yes,Yes,2,Yes,Yes,754.80,600-800€,6+(inches),3000-3500(mah),0-24(mp)
4,LG G8X ThinQ,LG,G8X ThinQ,4000,6.40,Yes,1080,2340,8,6000,...,Yes,Yes,1,No,No,599.88,400-600€,6+(inches),3500-4500(mah),0-24(mp)

In [37]:
data.to_csv('../Data_bases/data_for_presentation1.csv', index=False)

In [38]:
data['brand'].unique()

array(['OnePlus', 'Realme', 'Apple', 'LG', 'Samsung', 'Asus', 'Xiaomi',
       'Oppo', 'Huawei', 'Google', 'Nokia', 'HTC', 'Motorola', 'Honor',
       'Yu', 'Poco', 'Vivo', 'Nubia', 'Black Shark', 'Infinix', 'Lenovo',
       'Sony', 'Jio', 'Coolpad', 'Micromax', 'Smartron', 'LeEco',
       'BlackBerry', 'Gionee', 'Meizu', 'Panasonic', 'Tecno', 'InFocus',
       'Itel', '10.or', 'Lava', 'Cat', 'Lyf', 'Intex', 'Xolo', 'Acer',
       'Phicomm', 'Karbonn', 'Spice', 'iVoomi', 'Kult', 'Nuu Mobile',
       'Ziox', 'Zopo', 'ZTE', 'Onida', 'Microsoft', 'iBall', 'Mobiistar',
       'Comio', 'Videocon', 'Alcatel', 'Reach', 'Zen', 'Tambo', 'Razer',
       'Homtom', 'Lephone', 'Aqua', 'Celkon', 'Jivi', 'Billion', 'Swipe',
       'M-tech', 'Sansui', 'Zuk', 'TCL', 'mPhone', 'Blu', 'HP', 'Philips'],
      dtype=object)

In [48]:
def clean_brand(x):
    keep_list = ['Samsung','Apple','LG','Motorola','Huawei','Google',
                 'Sony','Microsoft','Nokia','10.or', 'Alcatel','OnePlus']
    return x if x in keep_list else "other"

data["brand_p"] = data["brand"].apply(clean_brand)

In [49]:
data

,name,brand,model,battery_capacity_(mah),screen_size_(inches),touchscreen,resolution_x,resolution_y,processor,ram_(mb),...,gps,number_of_sims,3g,4g/_lte,price,price_ranges,screen_size_range,battery_capacity_range,rear_camera_range,brand_p
0,OnePlus 7T Pro McLaren Edition,OnePlus,7T Pro McLaren Edition,4085,6.67,Yes,1440,3120,8,12000,...,Yes,2,Yes,Yes,707.98,600-800€,6+(inches),3500-4500(mah),32-48(mp),OnePlus
1,Realme X2 Pro,Realme,X2 Pro,4000,6.50,Yes,1080,2400,8,6000,...,Yes,2,Yes,Yes,335.99,200-400€,6+(inches),3500-4500(mah),48-64(mp),other
2,iPhone 11 Pro Max,Apple,iPhone 11 Pro Max,3969,6.50,Yes,1242,2688,6,4000,...,Yes,2,Yes,Yes,1282.80,1000+€,6+(inches),3500-4500(mah),0-24(mp),Apple
3,iPhone 11,Apple,iPhone 11,3110,6.10,Yes,828,1792,6,4000,...,Yes,2,Yes,Yes,754.80,600-800€,6+(inches),3000-3500(mah),0-24(mp),Apple
4,LG G8X ThinQ,LG,G8X ThinQ,4000,6.40,Yes,1080,2340,8,6000,...,Yes,1,No,No,599.88,400-600€,6+(inches),3500-4500(mah),0-24(mp),LG
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1354,Intex Aqua A2,Intex,Aqua A2,1500,4.00,Yes,480,800,4,512,...,Yes,2,Yes,No,31.19,<200€,3.0-4.0(inches),1010-2300(mah),0-24(mp),other
1355,Videocon Infinium Z51 Nova+,Videocon,Infinium Z51 Nova+,2000,5.00,Yes,480,854,4,1000,...,Yes,2,Yes,No,35.28,<200€,4.0-5.0(inches),1010-2300(mah),0-24(mp),other
1356,Intex Aqua Y4,Intex,Aqua Y4,1700,4.50,Yes,480,854,2,512,...,No,2,Yes,No,35.99,<200€,4.0-5.0(inches),1010-2300(mah),0-24(mp),other
1357,iBall Andi4 B20,iBall,Andi4 B20,1250,4.00,Yes,480,800,1,256,...,Yes,2,Yes,No,29.98,<200€,3.0-4.0(inches),1010-2300(mah),0-24(mp),other
1358,iBall Andi Avonte 5,iBall,Andi Avonte 5,2150,5.00,Yes,480,854,4,1000,...,Yes,2,Yes,No,47.99,<200€,4.0-5.0(inches),1010-2300(mah),0-24(mp),other

In [50]:
data.to_csv('../Data_bases/data_for_presentation_final.csv', index=False)